batch_size = 4
cls_fn = "cos_sim"
model = "cnn14"
base_epochs=100
weightgen_epochs=200
novel_epochs=50
save_ivl = 50
label_smoothing = 0
learning_rate = 0.000005
multilabel = false
omit_last_relu = false
sample_rate = 16000
use_class_weights = false
res1_dropout = 0.5
res2_dropout = 0.5
rese1_dropout = 0.5
rese1_fc_alpha = 0.25
rese2_fc_alpha = 0.25
rese2_dropout = 0.25
se_dropout = 0.5
se_fc_alpha = 0.25
simple_dropout = 0.5
use_prelu = true
se_prelu = false
to_print = true
to_time = true
to_graph = true
to_res = true
to_nep = true
train_phase = "base_trainall"
baseset="esc50"
novelset="esc50"
n_way = 5
k_shot = 4
data_dir ='/home/dxk/ds/'

