learning_rate=0.00025
cls_fn='cos_sim'
model = "samplecnn"
sample_rate=16000
batch_size=5
epochs=1
multilabel=true
use_class_weights=false
label_smoothing=0.0
se_fc_alpha=20.0
rese1_fc_alpha=20.0
rese2_fc_alpha=20.0
se_dropout=0.5
res1_dropout=0.5
res2_dropout=0.5
rese1_dropout=0.5
rese2_dropout=0.5
simple_dropout=0.5
save_ivl=0
load_emb=''
load_cls=''
load_model_by_tup='-1,-1'
omit_last_relu=true
use_prelu=true
se_prelu=false
to_print=true
to_time=true
to_graph=true
to_res=true
to_nep=false
train_phase='base_init'

