learning_rate=0.00025
cls_fn='cos_sim'
model = "samplecnn"
sample_rate=16000
batch_size=4
base_epochs=1
weightgen_epochs=10
novel_epochs=10
multilabel=false
use_class_weights=false
label_smoothing=0.0
se_fc_alpha=0.25
rese1_fc_alpha=0.25
rese2_fc_alpha=0.25
se_dropout=0.5
res1_dropout=0.5
res2_dropout=0.5
rese1_dropout=0.5
rese2_dropout=0.5
simple_dropout=0.5
save_ivl=0
load_emb=''
load_cls=''
load_model_by_tup='-1,-1'
omit_last_relu=true
use_prelu=true
se_prelu=false
to_print=true
to_time=true
to_graph=true
to_res=true
to_nep=false
train_phase='novel_valid'

n_way = 5
k_shot = 4
baseset="esc50"
novelset="esc50"

base_dir ='/home/dxk/ds/ESC-50-master'
novel_dir ='/home/dxk/ds/ESC-50-master'

