batch_size = 4
cls_fn = "cos_sim"
model = "samplecnn"
base_epochs=20
weightgen_epochs=50
novel_epochs=1
save_ivl = 0
label_smoothing = 0
learning_rate = 0.00025
multilabel = false
omit_last_relu = true
sample_rate = 16000
use_class_weights = false
res1_dropout = 0.5
res2_dropout = 0.5
rese1_dropout = 0.5
rese1_fc_alpha = 0.25
rese2_fc_alpha = 0.25
rese2_dropout = 0.25
se_dropout = 0.5
se_fc_alpha = 0.25
simple_dropout = 0.5
use_prelu = true
se_prelu = false
to_print = true
to_time = true
to_graph = true
to_res = true
to_nep = true
train_phase = "novel_valid"
baseset="esc50"
novelset="esc50"
n_way = 5
k_shot = 4

emb_load_num = 29
cls_load_num = 99
expr_num = 1711861663329
emb_idx = 0
cls_idx = 1
model_dir ='/media/dxk/tosh_ext/fscil/dfsl_rawwv/save'

save_dir = '/media/dxk/tosh_ext/fscil/dfsl_rawwv/save'
base_dir ='/home/dxk/ds/ESC-50-master'
novel_dir ='/home/dxk/ds/ESC-50-master'
