batch_size = 4
cls_fn = "cos_sim"
model = "samplecnn"
base_epochs=35
weightgen_epochs=1000
novel_epochs=1
save_ivl = 1000
label_smoothing = 0
learning_rate = 0.00025
learning_rate_weightgen = 0.1
multilabel = false
omit_last_relu = true
sample_rate = 16000
use_class_weights = false
res1_dropout = 0.5
res2_dropout = 0.5
rese1_dropout = 0.5
rese1_fc_alpha = 0.25
rese2_fc_alpha = 0.25
rese2_dropout = 0.25
se_dropout = 0.5
se_fc_alpha = 0.25
simple_dropout = 0.5
use_prelu = true
se_prelu = false
to_print = true
to_time = true
to_graph = true
to_res = true
to_nep = true
train_phase = "base_trainall"
#train_phase = "run_all"
baseset="esc50"
novelset="esc50"
n_way = 5
k_shot = 4
save_dir = '/media/dxk/tosh_ext/fscil/dfsl_rawwv/save'
base_dir ='/home/dxk/ds/ESC-50-master'
novel_dir ='/home/dxk/ds/ESC-50-master'

